### ISSUE TITLE
Fix Sqlite closing same thread issue.

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim_backend#62]
With #61 , a new error appear in webdav.
It happen occasionaly when we do webdav action but It does not seems to affect functionality.
It happen also each time we stop webdav process after doing some actions (tracimcli webdav start, do some webdav stuff, Ctrl+C to stop process).

```
Traceback (most recent call last):
  File "/home/me/.virtualenvs/tracim_backend/env/lib/python3.5/site-packages/sqlalchemy/pool.py", line 709, in _finalize_fairy
    fairy._reset(pool)
  File "/home/me/.virtualenvs/tracim_backend/env/lib/python3.5/site-packages/sqlalchemy/pool.py", line 880, in _reset
    pool._dialect.do_rollback(self)
  File "/home/me/.virtualenvs/tracim_backend/env/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 457, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 140484613187328 and this is thread id 140484588009216
Exception closing connection <sqlite3.Connection object at 0x7fc51fd971f0>
Traceback (most recent call last):
  File "/home/me/.virtualenvs/tracim_backend/env/lib/python3.5/site-packages/sqlalchemy/pool.py", line 709, in _finalize_fairy
    fairy._reset(pool)
  File "/home/me/.virtualenvs/tracim_backend/env/lib/python3.5/site-packages/sqlalchemy/pool.py", line 880, in _reset
    pool._dialect.do_rollback(self)
  File "/home/me/.virtualenvs/tracim_backend/env/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 457, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 140484613187328 and this is thread id 140484588009216

```

It's look like sqlalchemy-sessions are not closed in the thread they belong

**Comment by inkhey** [comment]
When launching same propfind command many time, error happened sometime:
`   curl -X PROPFIND "http://localhost:3030/w1/A" --user 'admin@admin.admin:admin@admin.admin' -k`

**Comment by inkhey** [comment]
This issue doesn't seem to affect at all result of commands. 
It happened also with normal pyramid web server after the same command many time (probably related to poolthread and not properly closed session).

To test this(webdav with curl test each 0.1 sec):
`watch -n 0.1 curl -X PROPFIND "http://localhost:3030" --user 'admin@admin.admin:admin@admin.admin' -k`
To test this(pyramid web app with httpie, test each 0.1 sec) :
`watch -n 0.1 http POST :6543/api/v2/sessions/login email="admin@admin.admin" password="admin@admin.admin"  Origin:localhost`
